{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  annotations:
    haproxy-ingress.github.io/rewrite-target: {{ .Values.ingress.rewriteTarget }}
spec:
  ingressClassName: haproxy
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $.Release.Name }}-svc-{{ $.Release.Namespace }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end}}
    {{- end}}
{{- end}}